/**
 * Outils e-commerce gratuits / freemium — APIs, apps, réseaux, plateformes.
 * Affichés uniquement pour le métier / catégorie e-commerce.
 */
export type EcommerceToolKind =
  | 'marketplace'
  | 'store'
  | 'payment'
  | 'shipping'
  | 'ads'
  | 'social'
  | 'analytics'
  | 'email'
  | 'design'
  | 'api'
  | 'crm'
  | 'dropship'

export type EcommerceTool = {
  id: string
  icon: string
  kind: EcommerceToolKind
  nameFr: string
  nameAr: string
  hintFr: string
  hintAr: string
  /** gratuit | freemium | open_source */
  pricing: 'free' | 'freemium' | 'open_source'
  url: string
  /** Action interne AZ Digital si applicable */
  internal?: 'digital' | 'ads' | 'affiliate' | 'dropship' | 'organic' | 'social'
}

export const ECOMMERCE_TOOL_KINDS: Array<{
  id: EcommerceToolKind
  labelFr: string
  labelAr: string
}> = [
  { id: 'store', labelFr: 'Boutique en ligne', labelAr: 'متجر إلكتروني' },
  { id: 'marketplace', labelFr: 'Marketplaces', labelAr: 'أسواق' },
  { id: 'dropship', labelFr: 'Dropshipping', labelAr: 'دروبشيبينغ' },
  { id: 'payment', labelFr: 'Paiements', labelAr: 'مدفوعات' },
  { id: 'shipping', labelFr: 'Livraison', labelAr: 'توصيل' },
  { id: 'social', labelFr: 'Réseaux sociaux', labelAr: 'شبكات اجتماعية' },
  { id: 'ads', labelFr: 'Publicité', labelAr: 'إعلانات' },
  { id: 'analytics', labelFr: 'Analytics', labelAr: 'تحليلات' },
  { id: 'email', labelFr: 'Email / CRM', labelAr: 'بريد / CRM' },
  { id: 'design', labelFr: 'Design / créas', labelAr: 'تصميم' },
  { id: 'api', labelFr: 'APIs & dev', labelAr: 'واجهات وبرمجيات' },
  { id: 'crm', labelFr: 'Support client', labelAr: 'دعم زبائن' },
]

/** Catalogue — gratuit ou freemium utilisable sans budget au démarrage */
export const ECOMMERCE_TOOLS: EcommerceTool[] = [
  // —— Boutique ——
  {
    id: 'woocommerce',
    icon: '🛒',
    kind: 'store',
    nameFr: 'WooCommerce',
    nameAr: 'ووكومرس',
    hintFr: 'Boutique WordPress open source — gratuit',
    hintAr: 'متجر ووردبريس مفتوح المصدر — مجاني',
    pricing: 'open_source',
    url: 'https://woocommerce.com/',
  },
  {
    id: 'prestashop',
    icon: '🏪',
    kind: 'store',
    nameFr: 'PrestaShop',
    nameAr: 'بريستاشوب',
    hintFr: 'CMS e-commerce open source',
    hintAr: 'نظام متجر مفتوح المصدر',
    pricing: 'open_source',
    url: 'https://www.prestashop.com/',
  },
  {
    id: 'medusa',
    icon: '🧬',
    kind: 'store',
    nameFr: 'Medusa.js',
    nameAr: 'ميدوسا',
    hintFr: 'Headless commerce open source + API',
    hintAr: 'تجارة headless مفتوحة + API',
    pricing: 'open_source',
    url: 'https://medusajs.com/',
  },
  {
    id: 'saleor',
    icon: '📦',
    kind: 'store',
    nameFr: 'Saleor',
    nameAr: 'سالور',
    hintFr: 'GraphQL commerce open source',
    hintAr: 'تجارة GraphQL مفتوحة',
    pricing: 'open_source',
    url: 'https://saleor.io/',
  },
  {
    id: 'shopify-trial',
    icon: '🛍️',
    kind: 'store',
    nameFr: 'Shopify (essai)',
    nameAr: 'شوبيفاي (تجربة)',
    hintFr: 'Essai gratuit puis freemium',
    hintAr: 'تجربة مجانية ثم freemium',
    pricing: 'freemium',
    url: 'https://www.shopify.com/',
  },
  {
    id: 'ecwid',
    icon: '📱',
    kind: 'store',
    nameFr: 'Ecwid',
    nameAr: 'إكويد',
    hintFr: 'Mini-boutique freemium (plan gratuit)',
    hintAr: 'متجر صغير freemium',
    pricing: 'freemium',
    url: 'https://www.ecwid.com/',
  },
  {
    id: 'az-digital-shop',
    icon: '🚀',
    kind: 'store',
    nameFr: 'AZ Digital boutique',
    nameAr: 'متجر AZ Digital',
    hintFr: 'Vente digitale + WhatsApp dans l’app',
    hintAr: 'بيع رقمي + واتساب داخل التطبيق',
    pricing: 'free',
    url: '',
    internal: 'digital',
  },

  // —— Marketplaces ——
  {
    id: 'facebook-shop',
    icon: '📘',
    kind: 'marketplace',
    nameFr: 'Facebook Shop',
    nameAr: 'متجر فيسبوك',
    hintFr: 'Catalogue gratuit Meta Commerce',
    hintAr: 'كتالوج مجاني ميتا',
    pricing: 'free',
    url: 'https://www.facebook.com/commerce/',
    internal: 'social',
  },
  {
    id: 'instagram-shop',
    icon: '📸',
    kind: 'marketplace',
    nameFr: 'Instagram Shopping',
    nameAr: 'تسوق إنستغرام',
    hintFr: 'Tags produits + boutique IG',
    hintAr: 'وسوم منتجات + متجر إنستا',
    pricing: 'free',
    url: 'https://business.instagram.com/shopping',
    internal: 'social',
  },
  {
    id: 'google-merchant',
    icon: '🏷️',
    kind: 'marketplace',
    nameFr: 'Google Merchant Center',
    nameAr: 'مركز تجار جوجل',
    hintFr: 'Flux produits gratuits (Shopping)',
    hintAr: 'خلاصة منتجات مجانية',
    pricing: 'free',
    url: 'https://merchants.google.com/',
  },
  {
    id: 'jumia-seller',
    icon: '🧡',
    kind: 'marketplace',
    nameFr: 'Jumia Seller',
    nameAr: 'جوميا بائع',
    hintFr: 'Marketplace Afrique / DZ',
    hintAr: 'سوق أفريقيا / الجزائر',
    pricing: 'freemium',
    url: 'https://sellercenter.jumia.dz/',
  },
  {
    id: 'ouedkniss',
    icon: '🟢',
    kind: 'marketplace',
    nameFr: 'Ouedkniss',
    nameAr: 'واد كنيس',
    hintFr: 'Petites annonces DZ (gratuit)',
    hintAr: 'إعلانات الجزائر (مجاني)',
    pricing: 'free',
    url: 'https://www.ouedkniss.com/',
  },

  // —— Dropship ——
  {
    id: 'taager',
    icon: '🚚',
    kind: 'dropship',
    nameFr: 'Taager',
    nameAr: 'تاجر',
    hintFr: 'Dropship MENA — API dans AZ Digital',
    hintAr: 'دروبشيب MENA — API في AZ Digital',
    pricing: 'freemium',
    url: 'https://taager.com/',
    internal: 'dropship',
  },
  {
    id: 'easyorders',
    icon: '📋',
    kind: 'dropship',
    nameFr: 'EasyOrders',
    nameAr: 'إيزي أوردرز',
    hintFr: 'Commandes + dropship DZ',
    hintAr: 'طلبات + دروبشيب الجزائر',
    pricing: 'freemium',
    url: 'https://easy-orders.net/',
    internal: 'dropship',
  },
  {
    id: 'aliexpress',
    icon: '🌏',
    kind: 'dropship',
    nameFr: 'AliExpress',
    nameAr: 'علي إكسبريس',
    hintFr: 'Catalogue mondial + affiliation',
    hintAr: 'كتالوج عالمي + عمولة',
    pricing: 'free',
    url: 'https://www.aliexpress.com/',
    internal: 'dropship',
  },
  {
    id: 'cj-dropshipping',
    icon: '✈️',
    kind: 'dropship',
    nameFr: 'CJ Dropshipping',
    nameAr: 'سي جي دروبشيبينغ',
    hintFr: 'API dropship + entrepôts',
    hintAr: 'API دروبشيب + مستودعات',
    pricing: 'freemium',
    url: 'https://cjdropshipping.com/',
    internal: 'dropship',
  },
  {
    id: 'printful',
    icon: '👕',
    kind: 'dropship',
    nameFr: 'Printful',
    nameAr: 'برينتفول',
    hintFr: 'Print-on-demand freemium',
    hintAr: 'طباعة عند الطلب',
    pricing: 'freemium',
    url: 'https://www.printful.com/',
  },

  // —— Paiements ——
  {
    id: 'stripe',
    icon: '💳',
    kind: 'payment',
    nameFr: 'Stripe',
    nameAr: 'سترايب',
    hintFr: 'Paiements en ligne + API (selon pays)',
    hintAr: 'دفع أونلاين + API',
    pricing: 'freemium',
    url: 'https://stripe.com/',
  },
  {
    id: 'paypal',
    icon: '🅿️',
    kind: 'payment',
    nameFr: 'PayPal',
    nameAr: 'باي بال',
    hintFr: 'Compte gratuit + boutons paiement',
    hintAr: 'حساب مجاني + أزرار دفع',
    pricing: 'freemium',
    url: 'https://www.paypal.com/',
  },
  {
    id: 'chargily',
    icon: '🇩🇿',
    kind: 'payment',
    nameFr: 'Chargily Pay',
    nameAr: 'شارجيلي',
    hintFr: 'Paiement DZ (EDAHABIA / CIB) + API',
    hintAr: 'دفع الجزائر + API',
    pricing: 'freemium',
    url: 'https://chargily.com/',
  },
  {
    id: 'baridimob',
    icon: '🏦',
    kind: 'payment',
    nameFr: 'BaridiMob / CCP',
    nameAr: 'بريدي موب / CCP',
    hintFr: 'Paiement local DZ (manuel / virement)',
    hintAr: 'دفع محلي جزائري',
    pricing: 'free',
    url: 'https://baridimob.poste.dz/',
  },
  {
    id: 'flouci',
    icon: '🇹🇳',
    kind: 'payment',
    nameFr: 'Flouci',
    nameAr: 'فلوسي',
    hintFr: 'Paiement mobile Tunisie',
    hintAr: 'دفع جوّال تونس',
    pricing: 'freemium',
    url: 'https://flouci.com/',
  },
  {
    id: 'wave',
    icon: '🌊',
    kind: 'payment',
    nameFr: 'Wave',
    nameAr: 'ويف',
    hintFr: 'Mobile money Afrique de l’Ouest',
    hintAr: 'موبايل ماني غرب أفريقيا',
    pricing: 'freemium',
    url: 'https://www.wave.com/',
  },
  {
    id: 'orange-money',
    icon: '🟠',
    kind: 'payment',
    nameFr: 'Orange Money',
    nameAr: 'أورنج موني',
    hintFr: 'Portefeuille mobile (SN, CI, CM…)',
    hintAr: 'محفظة جوّالة',
    pricing: 'freemium',
    url: 'https://www.orange.com/',
  },
  {
    id: 'mada',
    icon: '🇸🇦',
    kind: 'payment',
    nameFr: 'Mada / STC Pay',
    nameAr: 'مدى / STC Pay',
    hintFr: 'Paiements Arabie saoudite',
    hintAr: 'مدفوعات السعودية',
    pricing: 'freemium',
    url: 'https://www.mada.com.sa/',
  },

  // —— Livraison ——
  {
    id: 'yalidine',
    icon: '📮',
    kind: 'shipping',
    nameFr: 'Yalidine',
    nameAr: 'ياليدين',
    hintFr: 'Livraison DZ + API freemium',
    hintAr: 'توصيل الجزائر + API',
    pricing: 'freemium',
    url: 'https://www.yalidine.com/',
  },
  {
    id: 'zr-express',
    icon: '📦',
    kind: 'shipping',
    nameFr: 'ZR Express',
    nameAr: 'زد آر إكسبريس',
    hintFr: 'Livraison e-com DZ',
    hintAr: 'توصيل تجارة إلكترونية',
    pricing: 'freemium',
    url: 'https://zrexpress.dz/',
  },
  {
    id: 'maystro',
    icon: '🚛',
    kind: 'shipping',
    nameFr: 'Maystro Delivery',
    nameAr: 'مايسترو',
    hintFr: 'Logistique e-com Algérie',
    hintAr: 'لوجستيك تجارة إلكترونية',
    pricing: 'freemium',
    url: 'https://maystro-delivery.com/',
  },

  // —— Réseaux ——
  {
    id: 'meta-business',
    icon: '👥',
    kind: 'social',
    nameFr: 'Meta Business Suite',
    nameAr: 'مجموعة أعمال ميتا',
    hintFr: 'FB + IG gratuits — lier dans AZ Digital',
    hintAr: 'فيسبوك + إنستا — اربط في AZ Digital',
    pricing: 'free',
    url: 'https://business.facebook.com/',
    internal: 'social',
  },
  {
    id: 'tiktok-business',
    icon: '🎵',
    kind: 'social',
    nameFr: 'TikTok Business',
    nameAr: 'تيك توك أعمال',
    hintFr: 'Compte pro + organique gratuit',
    hintAr: 'حساب أعمال + محتوى مجاني',
    pricing: 'free',
    url: 'https://www.tiktok.com/business/',
    internal: 'social',
  },
  {
    id: 'whatsapp-business',
    icon: '💬',
    kind: 'social',
    nameFr: 'WhatsApp Business',
    nameAr: 'واتساب أعمال',
    hintFr: 'Catalogue + statuts gratuits',
    hintAr: 'كتالوج + حالات مجانية',
    pricing: 'free',
    url: 'https://www.whatsapp.com/business/',
    internal: 'social',
  },
  {
    id: 'telegram',
    icon: '✈️',
    kind: 'social',
    nameFr: 'Telegram',
    nameAr: 'تيليغرام',
    hintFr: 'Canal / boutique bot gratuit',
    hintAr: 'قناة / بوت متجر مجاني',
    pricing: 'free',
    url: 'https://telegram.org/',
  },
  {
    id: 'pinterest',
    icon: '📌',
    kind: 'social',
    nameFr: 'Pinterest Business',
    nameAr: 'بينتيريست أعمال',
    hintFr: 'Pins produits gratuits',
    hintAr: 'منشورات منتجات مجانية',
    pricing: 'free',
    url: 'https://business.pinterest.com/',
  },
  {
    id: 'youtube',
    icon: '▶️',
    kind: 'social',
    nameFr: 'YouTube',
    nameAr: 'يوتيوب',
    hintFr: 'Vidéos organiques + AdSense',
    hintAr: 'فيديوهات عضوية + أدسنس',
    pricing: 'free',
    url: 'https://www.youtube.com/',
  },

  // —— Pubs ——
  {
    id: 'meta-ads',
    icon: '📣',
    kind: 'ads',
    nameFr: 'Meta Ads Manager',
    nameAr: 'مدير إعلانات ميتا',
    hintFr: 'Pubs FB/IG — setup dans AZ Digital',
    hintAr: 'إعلانات فيسبوك — إعداد في AZ Digital',
    pricing: 'freemium',
    url: 'https://www.facebook.com/adsmanager',
    internal: 'ads',
  },
  {
    id: 'google-ads',
    icon: '🔍',
    kind: 'ads',
    nameFr: 'Google Ads',
    nameAr: 'إعلانات جوجل',
    hintFr: 'Search / Shopping / YouTube',
    hintAr: 'بحث / تسوق / يوتيوب',
    pricing: 'freemium',
    url: 'https://ads.google.com/',
    internal: 'ads',
  },
  {
    id: 'tiktok-ads',
    icon: '🎬',
    kind: 'ads',
    nameFr: 'TikTok Ads',
    nameAr: 'إعلانات تيك توك',
    hintFr: 'Spark Ads + organique',
    hintAr: 'سبارك + عضوي',
    pricing: 'freemium',
    url: 'https://ads.tiktok.com/',
    internal: 'ads',
  },
  {
    id: 'google-adsense',
    icon: '📰',
    kind: 'ads',
    nameFr: 'Google AdSense',
    nameAr: 'جوجل أدسنس',
    hintFr: 'Monétiser contenu (gratuit à rejoindre)',
    hintAr: 'ربح من المحتوى',
    pricing: 'free',
    url: 'https://www.google.com/adsense/',
    internal: 'ads',
  },

  // —— Analytics ——
  {
    id: 'ga4',
    icon: '📊',
    kind: 'analytics',
    nameFr: 'Google Analytics 4',
    nameAr: 'تحليلات جوجل 4',
    hintFr: 'Analytics gratuit',
    hintAr: 'تحليلات مجانية',
    pricing: 'free',
    url: 'https://analytics.google.com/',
  },
  {
    id: 'search-console',
    icon: '🧭',
    kind: 'analytics',
    nameFr: 'Search Console',
    nameAr: 'سيرش كونسول',
    hintFr: 'SEO gratuit Google',
    hintAr: 'تحسين ظهور مجاني',
    pricing: 'free',
    url: 'https://search.google.com/search-console',
  },
  {
    id: 'meta-pixel',
    icon: '🧿',
    kind: 'analytics',
    nameFr: 'Meta Pixel',
    nameAr: 'بكسل ميتا',
    hintFr: 'Suivi conversions gratuit',
    hintAr: 'تتبع تحويلات مجاني',
    pricing: 'free',
    url: 'https://www.facebook.com/business/tools/meta-pixel',
    internal: 'ads',
  },
  {
    id: 'clarity',
    icon: '🖱️',
    kind: 'analytics',
    nameFr: 'Microsoft Clarity',
    nameAr: 'كلاريتي',
    hintFr: 'Heatmaps & sessions gratuits',
    hintAr: 'خرائط حرارة مجانية',
    pricing: 'free',
    url: 'https://clarity.microsoft.com/',
  },
  {
    id: 'hotjar',
    icon: '🔥',
    kind: 'analytics',
    nameFr: 'Hotjar',
    nameAr: 'هوتجار',
    hintFr: 'Plan gratuit limité',
    hintAr: 'خطة مجانية محدودة',
    pricing: 'freemium',
    url: 'https://www.hotjar.com/',
  },

  // —— Email / CRM ——
  {
    id: 'mailchimp',
    icon: '🐵',
    kind: 'email',
    nameFr: 'Mailchimp',
    nameAr: 'ميل تشيمب',
    hintFr: 'Email marketing freemium',
    hintAr: 'تسويق بالبريد freemium',
    pricing: 'freemium',
    url: 'https://mailchimp.com/',
  },
  {
    id: 'brevo',
    icon: '✉️',
    kind: 'email',
    nameFr: 'Brevo (Sendinblue)',
    nameAr: 'بريفو',
    hintFr: 'Email + SMS freemium',
    hintAr: 'بريد + SMS freemium',
    pricing: 'freemium',
    url: 'https://www.brevo.com/',
  },
  {
    id: 'substack',
    icon: '📝',
    kind: 'email',
    nameFr: 'Substack',
    nameAr: 'سابستاك',
    hintFr: 'Newsletter gratuite',
    hintAr: 'نشرة بريدية مجانية',
    pricing: 'free',
    url: 'https://substack.com/',
  },

  // —— Design ——
  {
    id: 'canva',
    icon: '🎨',
    kind: 'design',
    nameFr: 'Canva',
    nameAr: 'كانفا',
    hintFr: 'Visuels pubs / stories freemium',
    hintAr: 'تصاميم إعلان freemium',
    pricing: 'freemium',
    url: 'https://www.canva.com/',
  },
  {
    id: 'capcut',
    icon: '✂️',
    kind: 'design',
    nameFr: 'CapCut',
    nameAr: 'كاب كات',
    hintFr: 'Montage vidéo TikTok gratuit',
    hintAr: 'مونتاج فيديو مجاني',
    pricing: 'free',
    url: 'https://www.capcut.com/',
  },
  {
    id: 'removebg',
    icon: '🖼️',
    kind: 'design',
    nameFr: 'remove.bg',
    nameAr: 'إزالة خلفية',
    hintFr: 'Fond transparent (quota gratuit)',
    hintAr: 'خلفية شفافة (حصة مجانية)',
    pricing: 'freemium',
    url: 'https://www.remove.bg/',
  },
  {
    id: 'photopea',
    icon: '🖌️',
    kind: 'design',
    nameFr: 'Photopea',
    nameAr: 'فوتوبيا',
    hintFr: 'Photoshop dans le navigateur (gratuit)',
    hintAr: 'فوتوشوب في المتصفح مجاناً',
    pricing: 'free',
    url: 'https://www.photopea.com/',
  },

  // —— APIs ——
  {
    id: 'meta-graph',
    icon: '🔌',
    kind: 'api',
    nameFr: 'Meta Graph API',
    nameAr: 'واجهة ميتا',
    hintFr: 'Publier FB/IG depuis AZ Digital',
    hintAr: 'نشر فيسبوك من AZ Digital',
    pricing: 'free',
    url: 'https://developers.facebook.com/',
    internal: 'social',
  },
  {
    id: 'open-exchange',
    icon: '💱',
    kind: 'api',
    nameFr: 'Open Exchange Rates',
    nameAr: 'أسعار صرف مفتوحة',
    hintFr: 'Taux de change (plan gratuit)',
    hintAr: 'أسعار العملات (مجاني)',
    pricing: 'freemium',
    url: 'https://openexchangerates.org/',
  },
  {
    id: 'dummyjson',
    icon: '🧪',
    kind: 'api',
    nameFr: 'DummyJSON / Fake Store',
    nameAr: 'بيانات تجريبية',
    hintFr: 'API produits de test gratuite',
    hintAr: 'API منتجات تجريبية مجانية',
    pricing: 'free',
    url: 'https://dummyjson.com/',
  },
  {
    id: 'vercel',
    icon: '▲',
    kind: 'api',
    nameFr: 'Vercel / Netlify',
    nameAr: 'فيرسل / نتليفاي',
    hintFr: 'Hébergement landing gratuit',
    hintAr: 'استضافة صفحة هبوط مجانية',
    pricing: 'freemium',
    url: 'https://vercel.com/',
  },

  // —— Support ——
  {
    id: 'tawk',
    icon: '💚',
    kind: 'crm',
    nameFr: 'Tawk.to',
    nameAr: 'توك تو',
    hintFr: 'Chat live 100 % gratuit',
    hintAr: 'دردشة مباشرة مجانية بالكامل',
    pricing: 'free',
    url: 'https://www.tawk.to/',
  },
  {
    id: 'crisp',
    icon: '💬',
    kind: 'crm',
    nameFr: 'Crisp',
    nameAr: 'كريسب',
    hintFr: 'Chat freemium',
    hintAr: 'دردشة freemium',
    pricing: 'freemium',
    url: 'https://crisp.chat/',
  },
  {
    id: 'google-forms',
    icon: '📋',
    kind: 'crm',
    nameFr: 'Google Forms',
    nameAr: 'نماذج جوجل',
    hintFr: 'Commandes / leads gratuits',
    hintAr: 'طلبات / زبائن محتملون مجاناً',
    pricing: 'free',
    url: 'https://forms.google.com/',
  },

  // —— Affiliation ——
  {
    id: 'amazon-associates',
    icon: '📦',
    kind: 'marketplace',
    nameFr: 'Amazon Associates',
    nameAr: 'أمازون أسوشيتس',
    hintFr: 'Affiliation légale — dans AZ Digital',
    hintAr: 'عمولة قانونية — في AZ Digital',
    pricing: 'free',
    url: 'https://affiliate-program.amazon.com/',
    internal: 'affiliate',
  },
  {
    id: 'organic-az',
    icon: '🌱',
    kind: 'ads',
    nameFr: 'Campagne organique',
    nameAr: 'حملة عضوية',
    hintFr: 'Stories / prospects dans AZ Digital',
    hintAr: 'ستوري / prospects في AZ Digital',
    pricing: 'free',
    url: '',
    internal: 'organic',
  },
]

export function toolName(t: EcommerceTool, lang: 'fr' | 'ar'): string {
  return lang === 'ar' ? t.nameAr : t.nameFr
}

export function toolHint(t: EcommerceTool, lang: 'fr' | 'ar'): string {
  return lang === 'ar' ? t.hintAr : t.hintFr
}

export function pricingLabel(
  p: EcommerceTool['pricing'],
  lang: 'fr' | 'ar',
): string {
  if (lang === 'ar') {
    if (p === 'open_source') return 'مفتوح المصدر'
    if (p === 'freemium') return 'مجاني محدود'
    return 'مجاني'
  }
  if (p === 'open_source') return 'Open source'
  if (p === 'freemium') return 'Freemium'
  return 'Gratuit'
}
